# Setup
title:               Prueba
description:         "Prueba description"
url:                 http://www.lazzaro.com.ar
google_verify: HWO2jrvTo3rJLDCmPOSBRzGD6e68MbXw4Bgb1Lb9PDI
baseurl: "/"
permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]
highlighter: pygments
analytics_id: 'UA-56357606-1'

# About/contact
author:
  name:                Leonardo Lazzaro
  email:               "llazzaro@dc.uba.ar" # email here
  avatar:              img/avatar.jpg
  profile-pic:         img/profile-pic.jpg
  url      : http://www.lazzaro.com.ar
  github   : http://github.com/llazzaro
  twitter  : http://twitter.com/llazzaro
  facebook : http://facebook.com/lazzaroleonardo
  linkedin : http://linkedin.com/in/llazzaro



# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Leonardo Lazzaro
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

