baseURL = "https://www.lazzaro.com.ar"
languageCode = "en"
defaultContentLanguage = "en"
title = "Leonardo Lazzaro"
theme = "PaperMod"

# Pagination
[pagination]
  pagerSize = 10

# Parameters
[params]
  description = "Software engineer, Django expert, and author of 'Building Web Applications with Django'"
  dateformat = "2006-01-02"
  dateFormat = "2006-01-02"
  defaultTheme = "auto"
  disableThemeToggle = false
  displayFullLangName = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  hideMeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  showBreadCrumbs = false
  share = false
  ShowReadingTime = true
  ShowWordCount = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = false
  ShowPageNums = true
  ShowToc = true
  TocFuzzy = true
  TocLevels = 3
  UseHugoToc = true
  comments = false
  customCSS = []
  enableFullRSS = true
  enableHanEmph = true
  enableMathjax = true
  favicon = "/favicon.ico"
  keywords = []
  darkmode = false
  hideFooter = true
  
  [params.author]
    name = "Leonardo Lazzaro"
    bio = "Software engineer and Django expert based in Japan"
    
  [params.social]
    github = "llazzaro"
    twitter = "llazzaro"
    linkedin = "llazzaro"
    
  [params.HomeInfoParams]
    Title = "Hi there!"
    Content = "Welcome to my personal blog where I write about technology, programming, and other things I find interesting."

  [params.utterances]
    enable = false
    repo = ""
    issue_term = "pathname"
    label = "Comment"
    theme = "github-light"

# Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
    
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
