baseURL = "https://www.lazzaro.com.ar"
defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en"
paginate = 3
theme = "PaperMod"
title = "Leonardo Lazzaro"
darkMode = false

disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true

footnoteReturnLinkContents = "^"


[author]
    name = "Leonardo Lazzaro"
    abstract = "I'm a software engineer and a coffee enthusiast in Japan. My primary interest lies in the area of natural language processing."


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/post/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  identifier = "photography"
  name = "Photography"
  url = "/photography/"
  weight = 4

[params]
  customCSS = []
  dateFormat = "2006-01-02"
  description = ""
  enableFullRSS = true
  enableHanEmph = true
  enableMathjax = true
  favicon = "/favicon.ico"
  footnote = "Follow me on <a class=link href=https://github.com/llazzaro>GitHub</a> or <a class=link href=https://twitter.com/llazzaro>Twitter</a> | <a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh target=_blank rel=noopener>CC BY-NC-SA 4.0</a>"
  keywords = []
  darkmode = false
  hideFooter = true


# see https://utteranc.es for installation guide
[params.utterances]
  enable = false
  repo = ""
  issue_term = "pathname"
  label = "Comment"
  theme = "github-light"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

